### ISSUE TITLE
How to add and use custom node types in node pilot

### ISSUE THREAD

**Issue by ntziolis** [decentralized-authority/node-launcher#39]
Great project, we have been looking for straight forward control plain to run nodes in a docker / kubernetes cluster and node pilot seems to fit the buill just right. 

However we are looking to run node of networks that are just starting out. We don't assume you to add those into the officail list but we would love to be able to define our own custom node types. Looking at the sources for the existing node types it should be fairly straight forward. 

The question is:
If and if so how to configure node pilot in a way that it would use our custom node types?

**Comment by moatus** [comment]
We are open to any contributes to adding new types to Node Launcher. We've had recently integrations that were lead by developer contributors. Node Pilot uses Node Launcher as it's deployment engine, so nodes added to Node Launcher are simple to integrate into Node Pilot.

For Node Pilot specific questions, feel free to direct them to our community Discord: https://discord.com/invite/W9CrDBB44U

**Comment by ntziolis** [comment]
We would be happy to contribute but the node types we have in mind would be for extremely early stage projects, often alpha or earlier testnet only.

We participate in many early stage networks and we're looking for a control plane that understands that the containers we are running are crypto workloads. Node pilot for that bill perfectly.

Die to the early stage nature we assumed that it would clutter the official repo with too many (potentially short lived node types). Hence the request for the ability to deploy custom node types.

We see node pilot having the potential to greatly simplyfy the involvement of the community in new projects.

Medium term i can Imagine new projects being able and entring to publish a link to a GitHub repo or npm package that contains the code to stand up a node type in node pilot as part of their official launch plan.

What
