### ISSUE TITLE
Node pilot product plans & source

### ISSUE THREAD

**Issue by ntziolis** [decentralized-authority/node-launcher#40]
Are you planning to offer node pilot as a paid SaaS offering or are there plans to open source the node pilot server & interface itself? If so any pointers on timeframes?

Note:
We understand this is not the correct repo but in ack of better options chose this one.

**Comment by moatus** [comment]
Regarding open sourcing, we discussed our plans in Pocket's most recent ecosystem community call: https://youtu.be/up5jK-5Q6qA?t=2693

I don't have anything to announce on the SaaS side, but we are looking into options.
