### ISSUE TITLE
After upgrade to v0.12.4 pokt validator doesn't serve relays

### ISSUE THREAD

**Issue by immunity20** [decentralized-authority/node-launcher#45]
Got a session of ETH with zero rewards and poktscan respond with error " invalid JSON from provider", responded with 5xx
https://node-000.pokt.yanis.gr/v1 was giving 502 gateway error

on nginx error log files i saw errors about invalid `upstream pokt-000:{{RPC_PORT}}`
and on nginx pokt-000 conf file i see
![image](https://user-images.githubusercontent.com/17274326/163704449-c27a99f9-88b7-4fa9-a26e-b684868e1ab0.png)

More ppl have same errors

**Comment by immunity20** [comment]
Also
pokt-000.domain.com/v1 shows invalid https certificate
Although I think the certificates are for node-000.domain.com (page node-000.domain.com/v1 has green lock in url)

**Comment by immunity20** [comment]
![image](https://user-images.githubusercontent.com/17274326/163705561-fada5765-f146-410a-918a-2d9fc1de6cc5.png)

**Comment by moatus** [comment]
Resolved in v0.12.5
