### ISSUE TITLE
public port and public domain show exceptions but nothing has changed

### ISSUE THREAD

**Issue by y19818** [decentralized-authority/node-launcher#47]
[](https://cdn.discordapp.com/attachments/959132985922318346/966305422787117086/unknown.png)The top four states were normal until the node was restarted. No changes have been made
now only public ip is green
![image](https://user-images.githubusercontent.com/31287334/164288837-e9731289-2088-4896-a4cc-8a2019f491f8.png)

Does anybody know why that is pls

**Comment by moatus** [comment]
Node Pilot support is done via the Discord. This Github repo is only for the Node Launcher deployment engine.
